post_install() {
	post_upgrade
}

# Post upgrade
post_upgrade() {
	echo "Attempting to enable services..."
	systemctl enable btrfs-balance.timer
	systemctl enable btrfs-defrag.timer
	systemctl enable btrfs-scrub.timer
	systemctl enable btrfs-trim.timer
	systemctl enable systemd-oomd
	systemctl enable systemd-timesyncd
	systemctl enable ananicy-cpp
	systemctl enable irqbalance
	systemctl --global enable psd
	systemctl --global enable gamemoded
	plymouth-set-default-theme bgrt
}
