#!/usr/bin/env bash

declare -r config_dir='/etc/desktop-entry-hider/configs'
declare -r configs_list=($(ls $config_dir))

for f in "${configs_list[@]}"; do

	if [[ ! -f "/usr/share/applications/$f" ]]; then
		continue
	fi

	source "$config_dir/$f"

	# If file does not contain required string, append it
	if ! grep -q "$contain" "/usr/share/applications/$f"; then
		echo "Configuring $f"
		echo "$contain" >> "/usr/share/applications/$f"
	else
		echo "$f is already configured, skipping..."
	fi

done

exit 0
