name: Lint

on:
  push:
    branches: [main]
    paths:
      - '**/*.sh'
      - '**/*.bash'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.sh'
      - '**/*.bash'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    uses: shani8dev/shani-ci-commons/.github/workflows/lint.yml@main
    with:
      language: bash

  security:
    name: Security
    uses: shani8dev/shani-ci-commons/.github/workflows/security.yml@main
    with:
      scan-type: all
    needs: lint
